# Application
application_name_full                     : Raivo OTP
application_name_short                    : Raivo
application_subtitle                      : Simply the best authenticator
application_description                   : A native, lightweight, non-commercial and secure multi-factor authenticator that synchronises your one-time passwords across all of your Apple devices.
application_app_icon_link                 : img/app-icon.png
application_apple_app_store_ios_id        : 1459042137
application_apple_app_store_ios_link      : https://apps.apple.com/app/raivo-otp/id1459042137?platform=iphone
application_apple_app_store_ios_beta      : https://testflight.apple.com/join/F3t8jXrL
application_apple_app_store_mac_id        : 1498497896
application_apple_app_store_mac_link      : https://apps.apple.com/app/raivo-otp/id1498497896
application_presskit_link                 : https://github.com/raivo-otp/ios-application/tree/master/Assets

# Raivo (socials)
social_application_github                 : raivo-otp
social_application_twitter                : RaivoOTP

# Author (socials & details)
social_author_fullname                    : Mobime
social_author_github                      : mobime-org
social_author_twitter                     : 
social_author_paypal                      : 

# GitHub
github_ios_application_link               : https://github.com/raivo-otp/ios-application
github_ios_application_community_link     : https://github.com/raivo-otp/ios-application/graphs/contributors
github_macos_receiver_link                : https://github.com/raivo-otp/macos-receiver
github_apns_server_link                   : https://github.com/raivo-otp/apns-server
github_issuer_icons_link                  : https://github.com/raivo-otp/issuer-icons
github_marketing_website_link             : https://github.com/raivo-otp/marketing-website

# Features
features                                  :
  - title                                 : Synchronisation
    description                           : Sync your one-time passwords to iCloud and never lose access to them again.
    icon                                  : refresh-cw
  - title                                 : Local backup
    description                           : Stay in control. Export your one-time passwords to encrypted ZIP archives.
    icon                                  : download
  - title                                 : Customisation
    description                           : Add (custom) icons to your one-time passwords and apply effects to them.
    icon                                  : sliders
  - title                                 : Dark mode
    description                           : Discover the beauty of Raivo OTP's dark side with a fully featured dark mode.
    icon                                  : moon
  - title                                 : Powerful search
    description                           : Search through all of your one-time passwords with one tap under your thumb.
    icon                                  : search
  - title                                 : Native & open source
    description                           : Experience the fast native application built in Swift 5. And it's open source too!
    icon                                  : code
  
# Retrieve app release data from GitHub
jekyll_get_json:
  - data: changelog
    json: 'https://api.github.com/repos/raivo-otp/ios-application/releases'

# Template
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"
cover_image                               : img/headerimage.jpeg
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8
body_background_color                     : "#ffffff"
link_color                                : "#ec1438"
app_title_color                           : "#ffffff"
app_subtitle_color                        : "#ffffff"
app_description_color                     : "#ffffff"
feature_title_color                       : "#000000"
feature_text_color                        : "#666666"
feature_icons_foreground_color            : "#ec1438"
feature_icons_background_color            : "#e6e6e6"
social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"
footer_text_color                         : "#666666"

# Compress output HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  blanklines: false

# Compress output CSS
sass:
  style: compressed # You might prefer to minify using :compressed

# Exlude certain files from production builds
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - PRIVACY.md
  - README.md
  - SECURITY.md
  - vendor
  - Gemfile
  - Gemfile.lock
  - dotenv

# Force include CNAME for gh-pages deployment
include:
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

plugins:
  - jekyll-get-json
  - jekyll-remote-include
  
# Markdown rendering
markdown: kramdown
